### ISSUE TITLE
Multiple selection tickbox needs a re-think

### ISSUE THREAD

**Issue by philipjackson** [gliff-ai/curate#125]
The only effect of the "Select Multiple Images" button is to produce a delete button. It doesn't affect the ability to select multiple images; that is done by ctr/shift clicking with or without the tickbox activated. 

We need to display the delete button whenever any images are selected, regardless of if the "select multiple" box is checked. In which case, the only remaining purpose for the "select multiple" box would have no remaining purpose, and we should just replace it with a delete button that's always there. Or we could leave it in and have it enable single-click multiple selections (which it currently does not do), giving users a way to select multiple without using the keyboard.

**Comment by RoseBunker** [comment]
Thanks for explanation above. I picked up on this yesterday. I wrote in my notes: 

"“Select multiple images” doesn’t do what I thought it would. What difference does this button make to selecting the thumbnails I want, because I still have to hold Ctrl to select multiple?"

**Comment by ChasNelson1990** [comment]
@joshuajames-smith can we mark this as duplicate and close (as it's covered by #228)?

**Comment by joshuajames-smith** [comment]
> @joshuajames-smith can we mark this as duplicate and close (as it's covered by #228)?

Yes it's now a duplicate and I will have labelled this and will close!
