### ISSUE TITLE
Assign one label to multiple images

### ISSUE THREAD

**Issue by ChasNelson1990** [gliff-ai/curate#262]
## Is your feature request related to a problem? Please describe

Currently if you want to assign a label to 50 different images, you need to do it one by one.

## Describe the solution you'd like

Be able to select (as per multi-select for delete or assign) several images and assign the label once.
This could just be by clicking the label icon on one of the selected images, adding the label and then a popover asking if you'd like to apply that to all selected images? @joshuajames-smith - could you have a think about this?

# Describe alternatives you've considered

None

## Additional context

None

**Comment by ChasNelson1990** [comment]
Also - let's add a loading snackbar whilst labels are being applied.

**Comment by ChasNelson1990** [comment]
P.S. the loading bar is required... I accidentally refreshed the page *after* it showed the labels... but on refresh they'd gone. @philipjackson - is this a saving time issue again?

**Comment by ChasNelson1990** [comment]
Is there a way DOMINATE can batch the change requests a bit more generally? I think the issue is that it seems to be making a batch request and a refresh request for each and then conflict and it all goes wrong?

**Comment by ChasNelson1990** [comment]
Duplicate of #228 but with a twist?

**Comment by RoseBunker** [comment]
Came to add this as a suggestion but see it's already here. I think this is an important feature, especially as we advertise ourselves as 'saving time'.

**Comment by ChasNelson1990** [comment]
@joshuajames-smith can you merge this in with #228 please? Then mark as duplicate and close?

**Comment by joshuajames-smith** [comment]
relates to #228
