### ISSUE TITLE
When label box is open, selected image label icon should stay green

### ISSUE THREAD

**Issue by ChasNelson1990** [gliff-ai/curate#263]
## Is your feature request related to a problem? Please describe

![image](https://user-images.githubusercontent.com/7795189/140187563-cd23be9a-e6b2-4085-ad59-b5a4a31e5de0.png)

Q: Which of these images am I applying a label to?
A: In this case, the left, but in other cases the alignment could imply the middle. Or right.

## Describe the solution you'd like

The label icon should stay highlighted whilst the poppover is on.

**Comment by ChasNelson1990** [comment]
Also, when the label box opens, the cursor should snap to the New Label field - and the New Label Field should accept a Return key press as an "add label" cue.

**Comment by ChasNelson1990** [comment]
@joshuajames-smith can you merge this in with #228 please? Then mark as duplicate and close?

**Comment by joshuajames-smith** [comment]
relates to #228
