### ISSUE TITLE
Can't clear a filter?

### ISSUE THREAD

**Issue by ChasNelson1990** [gliff-ai/curate#27]
**Describe the bug**

Just playing with PR #26 and I can't actually clear a filter once it's been applied? This seems to be unintended behaviour?

**To Reproduce**

1.  Go to #26
2.  Click on the latest Azure deploy
3.  Set a filter on, for example, "ImageName" as "sample0"
4.  Clear the text field and re-search
5. Nothing happens

**Expected behavior**

Clearing the text field and researching should reset the search and/or there should be a reset button?

**Screenshots**

N/A

**Desktop (please complete the following information):**

- OS: Linux
- Browse: Chromium
- Version: 89.0.4389.114

**Additional context**

None

**Comment by philipjackson** [comment]
Fixed in [#26](https://github.com/gliff-ai/curate/pull/26)
