### ISSUE TITLE
Define file format and data types for metadata

### ISSUE THREAD

**Issue by SilviaZeta** [gliff-ai/curate#28]
**Is your feature request related to a problem? Please describe.**
At the moment CURATE expects the metadata to be stored in a JSON file. We need to decide what the final format will be, together with data types for each metadata field.

**Describe the solution you'd like**
See https://github.com/gliff-ai/curate/pull/26 for suggested changes to the code.

**Describe alternatives you've considered**
N/A

**Comment by ChasNelson1990** [comment]
Actually, we only want to force type on our metadata but the format we're using for DOMINATE allows custom metadata too, which we can't force.

As part of this can we only ever use proper datetimes or ISO datetime string?
