### ISSUE TITLE
Add Spinner in Curate

### ISSUE THREAD

**Issue by ChrisBaidoo** [gliff-ai/curate#280]
When you load CURATE, there is a blank screen until the images show.
Display a spinner instead of the blank screen whiles waiting for the images to load.

Our first attempt at this issue was unsuccessful as we couldn't make the default state of metadata to be null. 
It would have been nice to achieve this so that we can display the spinner only when the metadata is null, this way we prevent the situation where the spinner shows all the time even when you don't have any images in the metadata array.  

One way to fix this would be to rewrite CURATE as a functional component?

**Comment by joshuajames-smith** [comment]
https://github.com/gliff-ai/curate/issues/313 handles the loading via `skeleton screens` as opposed to a `spinner`
