### ISSUE TITLE
Remember and suggestion labels already applied

### ISSUE THREAD

**Issue by RoseBunker** [gliff-ai/curate#291]
## Is your feature request related to a problem? Please describe

Since I can't currently assign one label to multiple images in one action, I had to add labels individually. In doing this, I then had to type each label every time. 

## Describe the solution you'd like

If I have already used a label (e.g. "variable 1", "variable 2"), and I want to add that label to another image, rather than type the whole thing again and again, can a drop down appear with the labels that I have already used? (From which I can select the one I want.)

## Describe alternatives you've considered

Not considered alternatives.

## Additional context

This issue on its own is probably not that big a deal, but combined with not being able to use return key to add label and not being able to add a label to multiple images at the same time, it is adding time and labour to the process.

**Comment by ChasNelson1990** [comment]
@joshuajames-smith can you merge this in with #228 please? Then mark as duplicate and close?

**Comment by joshuajames-smith** [comment]
relates to #228
