### ISSUE TITLE
Select/deselect all image labels but one

### ISSUE THREAD

**Issue by SilviaZeta** [gliff-ai/curate#31]
**Is your feature request related to a problem? Please describe.**
At the moment we can filter the images by multiple image-wise labels, selecting and deselecting with a click one label at a time. We could add the option to select and deselect all labels with a single click.

**Describe the solution you'd like**
We could add a dropdown menu next to each label, with the option to select the given label, while at the same time deselecting all other labels (and vice versa, if the given label is already selected, unselect the given label, while selecting all other labels).

**Describe alternatives you've considered**
N/A

**Additional context**
No

**Comment by joshuajames-smith** [comment]
I like the idea of adding 'select all' and 'deselect all' options and I am trying to build them into my designs. Me and Chas also talked over the idea this afternoon and we thought about the possibility of when you double click on a label that this action would 'deselect all but the clicked' or 'select all but the clicked'? I've put together a quick example below to show what i mean!

Action: double click on label 1 which deselects label 2-6 but selects label 1
![Annotation Labels - selected](https://user-images.githubusercontent.com/83074763/117482735-b563ca00-af5c-11eb-86a5-1a52da30d48f.png)

Action: double click on label 1 which deselects label 1 but selects label 2-6
![Annotation Labels - deselected](https://user-images.githubusercontent.com/83074763/117482738-b5fc6080-af5c-11eb-948a-bc4a07385e7a.png)

**Comment by SilviaZeta** [comment]
Nice! Also, I like the double-click as an alternative to the dropdown.
